apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observ-service-monitor
  labels:
    app: golang-observ-svc
spec:
  selector:
    matchLabels:
      app: golang-observ-svc
  endpoints:
  - port: http
    path: /metrics
    interval: 30s



